apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: streaming-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: yourdockerhub/auth-service:1.0
          ports:
            - containerPort: 3001
          env:
            - name: MONGO_URI
              value: mongodb://mongo:27017/streamingdb
            - name: NODE_ENV
              value: production