apiVersion: v1
kind: Service
metadata:
  name: streaming-service
  namespace: streaming-app
spec:
  type: ClusterIP
  selector:
    app: streaming-service
  ports:
    - port: 3002
      targetPort: 3002